---
abstract: 'A Bash::Completion plugin for writing App::Cmd plugins'
author:
  - 'Rob Hoelz <rob@hoelz.ro>'
build_requires:
  Bash::Completion::Plugin::Test: 0
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bash-Completion-Plugins-App-Cmd
requires:
  App::Cmd: 0
  Bash::Completion: 0
  Class::Load: 0
  parent: 0
  perl: v5.8.8
resources:
  bugtracker: https://github.com/hoelzro/bash-completion-plugins-app-cmd/issues
  homepage: https://github.com/hoelzro/bash-completion-plugins-app-cmd
  repository: https://github.com/hoelzro/bash-completion-plugins-app-cmd.git
version: 0.01
